version: "3.8"

services:
  srs:
    image: ghcr.io/korjavin/german-conjuctions-trainer:master
    container_name: gct
    networks:
      - vaultwarden_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gct.rule=Host(`${DNS_NAME}`)"
      - "traefik.http.routers.gct.entrypoints=websecure"
      - "traefik.http.routers.gct.tls.certresolver=myresolver"
      - "io.containers.autoupdate=image"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_URL=${OPENAI_URL}
      - MODEL_NAME=${MODEL}
      - DB_PATH=/app/data/gct.db
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URL=${GOOGLE_REDIRECT_URL}
      - GOOGLE_ADMIN_ID=${GOOGLE_ADMIN_ID}

networks:
  vaultwarden_default:
    external: true
